USE learnai_db;

-- ============================================================
-- Node.js Quiz (lesson_id = 1062)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1062, 'What is Node.js?', 'A browser-based JavaScript engine', 'A server-side JavaScript runtime built on Chrome V8', 'A CSS framework', 'A database management system', 'B', 'Node.js is a server-side JavaScript runtime environment built on Chrome\'s V8 JavaScript engine.', 1),
(1062, 'Which command initializes a new Node.js project?', 'node start', 'npm init', 'node create', 'npm start', 'B', 'npm init creates a package.json file which initializes a new Node.js project.', 2),
(1062, 'What does the require() function do in Node.js?', 'Starts the server', 'Imports a module', 'Creates a database connection', 'Defines a route', 'B', 'require() is used to import modules (built-in, npm packages, or local files) in Node.js.', 3),
(1062, 'Which module is used to create an HTTP server in Node.js?', 'fs', 'path', 'http', 'url', 'C', 'The built-in http module provides utilities for creating HTTP servers and clients.', 4),
(1062, 'What is npm?', 'Node Package Manager', 'New Programming Method', 'Node Process Monitor', 'Network Protocol Manager', 'A', 'npm stands for Node Package Manager — it is used to install and manage JavaScript packages.', 5),
(1062, 'What is the event loop in Node.js?', 'A loop that runs forever', 'A mechanism that handles asynchronous callbacks', 'A type of for loop', 'A database query loop', 'B', 'The event loop is what allows Node.js to perform non-blocking I/O operations by offloading operations to the system kernel.', 6),
(1062, 'Which of the following is used to read a file in Node.js?', 'fs.readFile()', 'file.read()', 'io.read()', 'node.readFile()', 'A', 'fs.readFile() from the built-in fs (File System) module is used to read files asynchronously.', 7),
(1062, 'What does res.json() do in Express.js?', 'Reads JSON from request', 'Sends a JSON response', 'Parses JSON body', 'Validates JSON schema', 'B', 'res.json() sends a JSON response with the correct Content-Type header set to application/json.', 8),
(1062, 'What is middleware in Express.js?', 'A database layer', 'Functions that execute during the request-response cycle', 'A type of route', 'A template engine', 'B', 'Middleware functions have access to the request object, response object, and the next middleware function in the cycle.', 9),
(1062, 'Which status code means "Not Found" in HTTP?', '200', '301', '404', '500', 'C', 'HTTP 404 means the requested resource could not be found on the server.', 10);

-- ============================================================
-- React Advanced Quiz (lesson_id = 1068)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1068, 'What does React.memo() do?', 'Memorizes the entire app state', 'Prevents re-rendering if props have not changed', 'Creates a memoized selector', 'Caches API responses', 'B', 'React.memo is a higher order component that memoizes the result, preventing unnecessary re-renders when props are unchanged.', 1),
(1068, 'What is the purpose of useCallback hook?', 'To cache a computed value', 'To memoize a function so it is not recreated on every render', 'To call an API', 'To manage side effects', 'B', 'useCallback returns a memoized callback function that only changes if one of the dependencies has changed.', 2),
(1068, 'What does useMemo return?', 'A memoized function', 'A memoized value', 'A memoized component', 'A memoized state', 'B', 'useMemo returns a memoized value — it recomputes only when one of its dependencies changes.', 3),
(1068, 'What is the Context API used for?', 'Making API calls', 'Sharing state across components without prop drilling', 'Managing local component state', 'Handling form validation', 'B', 'Context API provides a way to pass data through the component tree without having to pass props down manually at every level.', 4),
(1068, 'What is code splitting in React?', 'Breaking CSS into multiple files', 'Splitting your code into smaller chunks loaded on demand', 'Dividing a component into multiple files', 'Separating logic from UI', 'B', 'Code splitting allows you to split your code into various bundles which can then be loaded on demand, improving performance.', 5),
(1068, 'Which hook replaces Redux for complex state?', 'useState', 'useEffect', 'useReducer', 'useContext', 'C', 'useReducer is an alternative to useState for managing complex state logic, similar to how Redux works.', 6),
(1068, 'What is React.lazy() used for?', 'Delaying state updates', 'Lazy loading components', 'Lazy evaluation of expressions', 'Deferring event handlers', 'B', 'React.lazy() lets you render a dynamic import as a regular component, enabling lazy loading.', 7),
(1068, 'What is a custom hook?', 'A hook provided by React', 'A JavaScript function starting with "use" that calls other hooks', 'A class method', 'A lifecycle method', 'B', 'A custom hook is a JavaScript function whose name starts with "use" and that may call other hooks.', 8),
(1068, 'What does Suspense do in React?', 'Pauses rendering until a condition is met', 'Handles errors in components', 'Manages async state', 'Optimizes re-renders', 'A', 'Suspense lets you specify the loading indicator to show while waiting for lazy-loaded components or data to load.', 9),
(1068, 'What is prop drilling?', 'Passing props through many component layers unnecessarily', 'Drilling into an object to find a prop', 'A performance optimization', 'A testing technique', 'A', 'Prop drilling refers to passing data through multiple layers of components that do not need it, just to reach a deeply nested component.', 10);

-- ============================================================
-- DevOps Quiz (lesson_id = 1074)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1074, 'What is Docker?', 'A programming language', 'A containerization platform', 'A cloud provider', 'A version control system', 'B', 'Docker is a platform for developing, shipping, and running applications in containers.', 1),
(1074, 'What is a Docker container?', 'A virtual machine', 'A lightweight, standalone executable package of software', 'A cloud storage unit', 'A database instance', 'B', 'A container is a standard unit of software that packages code and all its dependencies so the application runs reliably.', 2),
(1074, 'What is Kubernetes used for?', 'Writing backend code', 'Container orchestration and management', 'Database management', 'Frontend development', 'B', 'Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.', 3),
(1074, 'What does CI/CD stand for?', 'Code Integration / Code Deployment', 'Continuous Integration / Continuous Delivery', 'Container Infrastructure / Container Deployment', 'Cloud Integration / Cloud Delivery', 'B', 'CI/CD stands for Continuous Integration and Continuous Delivery/Deployment — a method to frequently deliver apps to customers.', 4),
(1074, 'What is a Dockerfile?', 'A configuration file for Kubernetes', 'A text file with instructions to build a Docker image', 'A Docker network configuration', 'A Docker volume definition', 'B', 'A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image.', 5),
(1074, 'What is GitHub Actions?', 'A GitHub feature for code review', 'A CI/CD platform integrated with GitHub', 'A GitHub project management tool', 'A GitHub security scanner', 'B', 'GitHub Actions is a CI/CD platform that allows you to automate your build, test, and deployment pipeline.', 6),
(1074, 'What is a Kubernetes Pod?', 'A group of nodes', 'The smallest deployable unit in Kubernetes', 'A Kubernetes namespace', 'A Docker image', 'B', 'A Pod is the smallest and simplest Kubernetes object — it represents a set of running containers on your cluster.', 7),
(1074, 'What does docker-compose do?', 'Compiles Docker images', 'Defines and runs multi-container Docker applications', 'Monitors Docker containers', 'Pushes images to Docker Hub', 'B', 'Docker Compose is a tool for defining and running multi-container Docker applications using a YAML file.', 8),
(1074, 'What is Infrastructure as Code (IaC)?', 'Writing code inside infrastructure', 'Managing infrastructure through code and configuration files', 'A programming paradigm', 'A cloud billing model', 'B', 'IaC is the practice of managing and provisioning infrastructure through machine-readable configuration files rather than manual processes.', 9),
(1074, 'What is a load balancer?', 'A tool to measure server load', 'A device that distributes network traffic across multiple servers', 'A Kubernetes component', 'A Docker network driver', 'B', 'A load balancer distributes incoming network traffic across multiple backend servers to ensure no single server is overwhelmed.', 10);

-- ============================================================
-- UI/UX Quiz (lesson_id = 1080)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1080, 'What does UI stand for?', 'User Interaction', 'User Interface', 'Unified Integration', 'Universal Input', 'B', 'UI stands for User Interface — the visual elements users interact with in a product.', 1),
(1080, 'What does UX stand for?', 'User Experience', 'User Execution', 'Unified Experience', 'Universal Exchange', 'A', 'UX stands for User Experience — the overall experience a user has when interacting with a product.', 2),
(1080, 'What is a wireframe?', 'A finished design mockup', 'A low-fidelity skeletal outline of a design', 'A CSS framework', 'A type of prototype', 'B', 'A wireframe is a low-fidelity, simplified outline of your product that shows the structure and layout without visual design.', 3),
(1080, 'What is Figma?', 'A programming language', 'A collaborative UI design tool', 'A CSS preprocessor', 'A JavaScript framework', 'B', 'Figma is a cloud-based design tool used for creating UI designs, prototypes, and design systems collaboratively.', 4),
(1080, 'What is a design system?', 'A set of rules for developers', 'A collection of reusable components and guidelines for consistent design', 'A project management methodology', 'A color palette', 'B', 'A design system is a collection of reusable components, guided by clear standards, that can be assembled to build any number of applications.', 5),
(1080, 'What is the 60-30-10 rule in design?', 'A grid system', 'A color proportion rule: 60% dominant, 30% secondary, 10% accent', 'A typography scale', 'A spacing system', 'B', 'The 60-30-10 rule is a classic color rule that helps create a color palette: 60% dominant color, 30% secondary, 10% accent.', 6),
(1080, 'What is a user persona?', 'A real user account', 'A fictional character representing a user segment', 'A user authentication method', 'A UI component', 'B', 'A user persona is a fictional representation of your ideal customer based on market research and real data about your existing customers.', 7),
(1080, 'What is contrast ratio used for in design?', 'Measuring color brightness', 'Ensuring text is readable against its background for accessibility', 'Comparing two designs', 'Measuring image quality', 'B', 'Contrast ratio measures the difference in luminance between foreground and background colors, crucial for accessibility (WCAG guidelines).', 8),
(1080, 'What is a prototype in UX design?', 'The final product', 'An interactive simulation of a design to test with users', 'A wireframe', 'A design specification document', 'B', 'A prototype is an interactive model of your product that allows you to test and validate design decisions before development.', 9),
(1080, 'What does "affordance" mean in UX?', 'The cost of a design tool', 'A design property that suggests how an object should be used', 'The loading speed of a UI', 'A type of animation', 'B', 'Affordance refers to the properties of an object that suggest how it can be used — e.g., a button looks clickable.', 10);

-- ============================================================
-- Cybersecurity Quiz (lesson_id = 1086)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1086, 'What is a firewall?', 'A type of malware', 'A network security system that monitors and controls traffic', 'An encryption algorithm', 'A VPN protocol', 'B', 'A firewall is a network security device that monitors incoming and outgoing network traffic and decides whether to allow or block specific traffic.', 1),
(1086, 'What does HTTPS stand for?', 'HyperText Transfer Protocol Secure', 'High Transfer Protocol System', 'HyperText Transport Protocol Standard', 'Hybrid Transfer Protocol Service', 'A', 'HTTPS stands for HyperText Transfer Protocol Secure — it uses SSL/TLS to encrypt communication between browser and server.', 2),
(1086, 'What is SQL injection?', 'A way to speed up SQL queries', 'An attack that inserts malicious SQL code into a query', 'A database optimization technique', 'A type of SQL join', 'B', 'SQL injection is a code injection technique that might destroy your database by inserting malicious SQL statements into an entry field.', 3),
(1086, 'What is two-factor authentication (2FA)?', 'Using two passwords', 'A security process requiring two different forms of verification', 'Logging in from two devices', 'A type of encryption', 'B', '2FA adds an extra layer of security by requiring two types of credentials: something you know (password) and something you have (phone).', 4),
(1086, 'What is phishing?', 'A network scanning technique', 'A social engineering attack to steal credentials via fake communications', 'A type of encryption', 'A firewall bypass method', 'B', 'Phishing is a cybercrime where targets are contacted by email/phone by someone posing as a legitimate institution to lure them into providing sensitive data.', 5),
(1086, 'What does encryption do?', 'Deletes sensitive data', 'Converts data into an unreadable format to protect it', 'Compresses data', 'Backs up data', 'B', 'Encryption converts readable data (plaintext) into an unreadable format (ciphertext) that can only be decoded with the correct key.', 6),
(1086, 'What is a VPN?', 'A type of malware', 'A Virtual Private Network that encrypts internet traffic', 'A web browser', 'A firewall type', 'B', 'A VPN (Virtual Private Network) creates an encrypted connection over the internet, protecting your data and hiding your IP address.', 7),
(1086, 'What is the principle of least privilege?', 'Giving all users admin access', 'Granting users only the minimum access rights they need', 'Restricting all user access', 'A password policy', 'B', 'The principle of least privilege means giving users only the access rights they need to perform their job functions — nothing more.', 8),
(1086, 'What is a DDoS attack?', 'A data deletion attack', 'Overwhelming a server with traffic to make it unavailable', 'A database corruption attack', 'A DNS hijacking attack', 'B', 'A DDoS (Distributed Denial of Service) attack floods a target with internet traffic from multiple sources to disrupt normal service.', 9),
(1086, 'What is penetration testing?', 'Testing network speed', 'Simulating cyberattacks to find vulnerabilities before attackers do', 'Testing firewall rules', 'A type of malware scan', 'B', 'Penetration testing (pen testing) is an authorized simulated cyberattack on a system to evaluate its security and find vulnerabilities.', 10);

-- ============================================================
-- SQL Quiz (lesson_id = 1092)
-- ============================================================
INSERT IGNORE INTO quiz_questions (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, order_index) VALUES
(1092, 'What does SQL stand for?', 'Structured Query Language', 'Simple Query Language', 'Standard Query Logic', 'Sequential Query Language', 'A', 'SQL stands for Structured Query Language — the standard language for relational database management systems.', 1),
(1092, 'Which SQL command retrieves data from a table?', 'INSERT', 'UPDATE', 'SELECT', 'DELETE', 'C', 'SELECT is used to retrieve data from one or more tables in a database.', 2),
(1092, 'What does PRIMARY KEY do?', 'Encrypts a column', 'Uniquely identifies each row in a table', 'Creates an index', 'Links two tables', 'B', 'A PRIMARY KEY uniquely identifies each record in a table. It must contain unique values and cannot contain NULL.', 3),
(1092, 'What is a FOREIGN KEY?', 'A key used for encryption', 'A field that links to the PRIMARY KEY of another table', 'A unique identifier', 'A composite key', 'B', 'A FOREIGN KEY is a field (or collection of fields) in one table that refers to the PRIMARY KEY in another table, establishing a relationship.', 4),
(1092, 'What does JOIN do in SQL?', 'Combines rows from two or more tables based on a related column', 'Deletes duplicate rows', 'Sorts query results', 'Groups rows together', 'A', 'JOIN is used to combine rows from two or more tables based on a related column between them.', 5),
(1092, 'What is the difference between WHERE and HAVING?', 'No difference', 'WHERE filters rows before grouping; HAVING filters after grouping', 'HAVING filters rows; WHERE filters groups', 'WHERE is for numbers; HAVING is for strings', 'B', 'WHERE filters individual rows before any groupings are made. HAVING filters groups after the GROUP BY clause has been applied.', 6),
(1092, 'What does GROUP BY do?', 'Sorts results', 'Groups rows with the same values into summary rows', 'Filters rows', 'Joins tables', 'B', 'GROUP BY groups rows that have the same values in specified columns into summary rows, often used with aggregate functions.', 7),
(1092, 'Which aggregate function counts rows?', 'SUM()', 'AVG()', 'COUNT()', 'MAX()', 'C', 'COUNT() returns the number of rows that match a specified criterion.', 8),
(1092, 'What does normalization mean in databases?', 'Speeding up queries', 'Organizing data to reduce redundancy and improve integrity', 'Encrypting database tables', 'Backing up the database', 'B', 'Database